apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12.1
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "8Mi"
            limits:
              memory: "16Mi"
              cpu: "100m"
