apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-deployment
  # namespace: demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12.1
          ports:
            - containerPort: 80
